### ISSUE TITLE
ReadOnly shared object between forked Actors

### ISSUE THREAD

**Issue by vallettea** [untu/comedy#1]
Hello,
thanks for this awesome library.
I would like to know how to share an object between forked actors.

Here is an example:

```
var pile  = []

class Player {
  count(to) {
    console.log(pile.length);
  }
}

class Croupier {
  add(to) {
    pile.push(9);
  }
}

var actorSystem = actors();

actorSystem
  .rootActor()
  .then(function(rootActor) {
  	Promise.all([rootActor.createChild(Player, {mode: 'forked', clusterSize: 3}), rootActor.createChild(Croupier)])
  	.then(children => {
  		var player = children[0];
  		var croupier = children[1];
  		setInterval(() => player.send('count'), 10);
  		setInterval(() => croupier.send('add'), 1000)
	  })
  })
```

This example works when Player actors are not forked but as soon as they are, they can't access the list `pile` anymore. Player should only be able to read the object, only `Croupier` car modify the object.

The only solution I see is that each `Player` gets a copy of `pile` in a message, but I'm scared it will have  big memory footprint.

Any help appreciated.

**Comment by weekens** [comment]
Hi, @vallettea ! Thanks, for using Comedy!

As you noticed, when using actor model, you only rely on messaging, and you cannot rely on sharing anything stateful between actors.

In your example, the `pile` object should be an internal state of `Croupier` actor, and the `Player.count` implementation should ask the parent actor (root actor in your case) about the `pile` length by sending a message. The parent actor would forward this message to `Croupier` actor (you can use `Actor.forwardToChild` method for that). You can set your own behaviour definition for the root actor, where the forwarding would occur, just use the `root` actor system creation option for that.

```javascript
var actorSystem = actors({
  root: {
    initialize: function(selfActor) {
      return Promise
        // Spawn child actors during root actor initialization.
        .join(
          selfActor.createChild(Player, {mode: 'forked', clusterSize: 3}),
          selfActor.createChild(Croupier))
        .spread((playerActor, croupierActor) => {
          // Configure root actor to redirect 'count' message to Croupier actor.
          selfActor.forwardToChild(croupierActor, 'count');
        });
    }
  }
});
```

In the example above you spawn your `Croupier` and `Player` actors right inside root actor initialization to get a reference to `Croupier` actor instance and to declaratively set 'count' message forwarding from root actor to `Croupier` actor. You would also need to implement 'count' message in `Croupier` actor.

You're right that sending the whole state within each message is not an option. Just use messaging heavily. Feel free to define as many message handlers as you like, each one receiving messages as lightweight as possible.

I've mentioned some features (like `forwardToChild`), that are not yet documented, but they will be in the nearest time.

**Comment by vallettea** [comment]
Ok thanks for the clarification.
I'm closing this issue but I am writing another.

**Comment by vallettea** [comment]
Just for information, the code you pasted doesn't work for me. I get a `Unhandled rejection TypeError: Promise.join is not a function` ? I'm using node 6.9

**Comment by weekens** [comment]
Well, I wasn't actually checking this code - I've written it from scratch just to show an idea.

`Promise.join` is not a standard ES6 Promise function. It is only available if you use [Bluebird](http://bluebirdjs.com/) promise library (see http://bluebirdjs.com/docs/api/promise.join.html).
