### ISSUE TITLE
Ability to Address Actors by Id

### ISSUE THREAD

**Issue by WonderPanda** [untu/comedy#17]
Is there any support for being able to assign identifiers to actors upon creation such that they could be addressed generically? All the examples I've seen so far seem to rely on having an actual reference to the actor in memory which makes it harder to support messaging between different actors.

**Comment by weekens** [comment]
@WonderPanda , you can only reference actors by name, which is taken either from actor definition class or from `name` actor parameter upon actor creation. The unique ID for each actor is generated by the system and cannot be specified.

Also, currently, there is no actor lookup feature, so the actor name only gives you a possiblity to specify configuration in `actors.json`.
