### ISSUE TITLE
How to run actor compiled in ES6 as forked mode?

### ISSUE THREAD

**Issue by pola88** [untu/comedy#20]
Hi guys,

I'm trying to run an actor as forked mode and this actor class is compiled with babel, but when runs the actor I got the following error:

```
ReferenceError: _classCallCheck is not defined
```
What am I missing?
Thanks,

**Comment by ohanjanyanmiqayel** [comment]
Hey!
Currently I'm running actors wrote in ES6 style, and getting no error.
Can you try running code, using node 10 experimental-modules enabled, and see if you are still getting errors?

**Comment by pola88** [comment]
Let me try, I'm using node `8.9.3`

**Comment by weekens** [comment]
Hi! This seems like a regression. I was able to reproduce it. I'll release a fix shortly.

**Comment by weekens** [comment]
Released a fix in [1.4.0](https://github.com/untu/comedy/releases/tag/v1.4.0).

Also released a new [dynamic logger configuration](https://github.com/untu/comedy#dynamic-logger-configuration) feature.
