### ISSUE TITLE
Move all tests to TypeScript

### ISSUE THREAD

**Issue by weekens** [untu/comedy#25]
This is to ensure we always have proper type definitions and to avoid bugs like #24 .

**Comment by noctifer20** [comment]
I could help with this, but can I use async/await instead of bluebird?

**Comment by weekens** [comment]
@noctifer20 , you totally can!

**Comment by noctifer20** [comment]
Here is PR #34

**Comment by weekens** [comment]
Thanks @noctifer20 !
