### ISSUE TITLE
How to prevent it outputting to console the initial setup log

### ISSUE THREAD

**Issue by PhilAndrew** [untu/comedy#29]
When my actor system using Comedy runs it says on the console.

Mon Sep 10 2018 19:28:17 GMT+0800 (China Standard Time) - info: Loaded default actor configuration file: C:\home\projects\ContractPen\contractpen_node_client/actors.json
Mon Sep 10 2018 19:28:17 GMT+0800 (China Standard Time) - info: Resulting actor configuration: {}

How to prevent it from saying this upon startup on console? I don't want any output to console to occur.

**Comment by weekens** [comment]
@PhilAndrew , you can do it the following way:

```javascript
var actors = require('comedy');

var actorSystem = actors(); // Create an actor system.

actorSystem.getLog().setLevel(0);
```

**Comment by PhilAndrew** [comment]
Thankyou, problem fixed
