### ISSUE TITLE
Switchable Logger

### ISSUE THREAD

**Issue by aintnorest** [untu/comedy#31]
Is there an easy way to switch out the logger? The application I'm porting over is using bunyan and I'd prefer to not have to redo it through out.

**Comment by weekens** [comment]
There is some work needed to be put in order to make this work, but I think it's a matter of couple of days. I was expecting this kind of request. Will try to do in nearest time.

**Comment by weekens** [comment]
Added support for custom loggers in [v1.8.0](https://github.com/untu/comedy/releases/tag/v1.8.0). See example: https://github.com/untu/comedy-examples/blob/master/custom-logger-bunyan.js

**Comment by aintnorest** [comment]
I used your example and it worked great until I tried starting an actor in forked mode. I then got Error: Cannot serialize actor definition. I threw a console in and noticed it was the BunyanLoggerAdapter. I made sure to move all the requires into the class itself but that didn't seem to help so I switched it to use the module method of loading. That worked but with two problems. I now get a warning for:
 Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.
a lot and my second problem is I'm not sure how to pass in a name for the bunyan initialization.

**Comment by weekens** [comment]
I will look at `Promise.defer` warnings.

As for logger name: in the example it was hard-coded into `BunyanLoggerAdapter`. Clearly, this may be not what you want. My question is: how would you like this to be done instead?

**Comment by aintnorest** [comment]
Maybe a way to pass in customParameters as part of the configuration.

**Comment by weekens** [comment]
@aintnorest , I've implemented constructor parameters for custom logger. Please check `forked-bunyan-logger` branch from [comedy-examples](https://github.com/untu/comedy-examples) repo together with `custom-logger-params` branch from this repo and tell if it works for you.

As for `Promise.defer` error - I could not reproduce it in `forked-bunyan-logger` branch in examples even with current Comedy release.  Please try that example with release version and tell if you are able to see `Promise.defer` errors. If not, please send me your code example.

**Comment by aintnorest** [comment]
looks great thanks.

**Comment by weekens** [comment]
Fix released in [v.2.1.0](https://github.com/untu/comedy/releases/tag/v2.1.0).
