### ISSUE TITLE
Supervision support?

### ISSUE THREAD

**Issue by adolfosilva** [untu/comedy#35]
Are there any plans to support supervision like [Nact](https://nact.io/lesson/javascript/supervision](https://nact.io/lesson/javascript/supervision) and others do?

**Comment by weekens** [comment]
@adolfosilva , Comedy can automatically respawn crashed actors if you specify `onCrash: 'respawn'` in actor configuration. Other possible strategies like exponential backoff are not supported yet.

**Comment by adolfosilva** [comment]
@weekens That was it, not in the documentation. Thank you :+1: .

**Comment by weekens** [comment]
Added some [docs](https://github.com/untu/comedy#actor-respawning-supervision) for this feature.
