### ISSUE TITLE
Test dependencies in package

### ISSUE THREAD

**Issue by donvadicastro** [untu/comedy#65]
Next dependencies better to move from "dependencies" to "devDependencies"
```
    "@types/chai": "4.1.4",
    "@types/mocha": "5.2.2",
```

As a result of "required" dependencies, it can create conflicts with other test frameworks used in the project who consumes "comedy".

**Comment by weekens** [comment]
@donvadicastro , thanks for your report! Created #66

**Comment by weekens** [comment]
Fix released in version `2.1.5`.
