### ISSUE TITLE
Possibility of scaling to other machines rather than just processes

### ISSUE THREAD

**Issue by thalesmello** [untu/comedy#7]
I just found out about this project, and I find the scaling capabilities particularly interesting.

Just out of curiosity, have you considered the possibility of scaling out to other machines rather than just other processes?

It would be really interesting it we were able to configure an entire cluster, allocating actors to different machines, but using the same interface to communicate between them.

What would be the challenges in making something like this happen?

**Comment by weekens** [comment]
Hi! This is exactly what I'm working on right now in `remote-actors` branch. I plan to finish the initial version within nearest month.

The very basic things seem to be working (you can check the tests: [test-remote-actor.js](https://github.com/untu/comedy/blob/remote-actors/test/test-remote-actor.js)).

Still to be done:
- remote actor respawn
- Docker container for listening node
- named clusters (initial version with explicitly specified IPs)

Things to do after initial version is released:
- full-fledged custers with automatically joining listener nodes
- automatic code deployment (with node_modules)
- remote actor references
- more effecient serialization format (BSON, PSON, GZip, Smile - whatever gives the maximum throughput; this should also be configurable)

The most challenging part is clustering, I guess. But this stuff is already done at least in Akka, and there are standard protocols for that (Gossip). So nothing impossible. And in the first version we can get away with just manual cluster configuration.

Great to see you interested! Hopefully, Comedy will fit your needs!

**Comment by thalesmello** [comment]
@weekens It's really great to see your vision for this library. =)

I was researching different async patterns in JavaScript, particularly Actor pattern, and came across this one. By far, this was the better well-thought (and up-to-date) library I've come across. ;)

**Comment by weekens** [comment]
The initial version is ready and merged to master. Going to release in nearest days.
