### ISSUE TITLE
Vulnerability updates: underscore and winston

### ISSUE THREAD

**Issue by farnk05** [untu/comedy#78]
# Description
From the looks of this config
https://github.com/untu/comedy/blob/e523ff81378e47264dc6902c504934d1dd845e1b/appveyor.yml#L6

The two pr's #75 and #74 are blocked because a configuration to install the latest version of npm, and the latest npm doesn't run with the node 10 version in the CI checks

from pr 75's checks https://ci.appveyor.com/project/weekens/comedy/builds/43166798
`ERROR: npm is known not to run on Node.js v10.24.1`

The last time this seemed to pass was in PR #73 and it ran with npm version `7.20.5`
Can I create a PR to change the line above to ` npm i npm@7.20.5 -g`

**Comment by weekens** [comment]
Fix released in `2.1.6`. Thanks for reporting!
